FROM grafana/grafana:11.0.0

COPY config/datasource.yaml /usr/share/grafana/conf/provisioning/datasources/efirmino.yaml

COPY config/dashboard.yaml /usr/share/grafana/conf/provisioning/dashboards/efirmino.yaml