# Generated by Django 5.1.2 on 2024-10-15 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.CharField(max_length=50, default='AI')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
