# FROM node:18

# WORKDIR /usr/src/app

# COPY package*.json ./package.json

# RUN npm install

# COPY . .

# EXPOSE 3000

# WORKDIR /usr/src/app/ft_trans/pong/templates/js/utils

# CMD ["node", "server.js"]

FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./package.json

RUN npm install

COPY ./ft_trans/pong/templates/js/utils/server.js .

CMD ["node", "server.js"]
