# Generated by Django 5.0.7 on 2024-09-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
    ]
