"""
Django settings for ft_trans project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

import dj_database_url


def env_list(name):
    """Liste séparée par des virgules, vide si la variable est absente."""
    return [item.strip() for item in os.getenv(name, '').split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY manquant. Voir src/.env.example.")

DEBUG = os.getenv("DJANGO_DEBUG", "").lower() in ("1", "true", "yes")

APPEND_SLASH=False

# `*` acceptait n'importe quel Host, ce qui ouvre la porte au poisoning d'en-tête
# Host (liens de réinitialisation forgés, empoisonnement de cache).
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS") or (["*"] if DEBUG else [])

# Derrière nginx en local et derrière le routeur de la plateforme en production :
# sans cela Django croit toutes les requêtes en HTTP et fabrique de mauvaises URL.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'rest_framework_simplejwt',
    'pong',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Le frontend est servi par un hôte distinct en production : les origines
# autorisées sont déclarées explicitement plutôt qu'en dur.
CORS_ALLOWED_ORIGINS = env_list("ALLOWED_ORIGINS")

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env_list("ALLOWED_ORIGINS")

ROOT_URLCONF = 'ft_trans.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ft_trans.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# En production, Neon fournit une DATABASE_URL unique. En local, compose passe
# encore les variables séparées. `postgresql_psycopg2` n'existe plus depuis
# longtemps : le backend s'appelle `postgresql` et détecte psycopg 3 tout seul.
_DATABASE_URL = os.getenv("DATABASE_URL")
if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,  # Neon facture au temps de calcul : on garde la connexion
            # SQLite n'a pas de TLS : la contrainte ne vaut que pour Postgres,
            # ce qui permet aussi de faire tourner les contrôles sans serveur.
            ssl_require=_DATABASE_URL.startswith(('postgres://', 'postgresql://')),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DJANGO_DB_NAME"),
            'USER': os.getenv("POSTGRES_USER"),
            'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
            'HOST': os.getenv("POSTGRES_HOST"),
            'PORT': os.getenv("POSTGRES_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = '/static'

# Avatars envoyés par les utilisateurs. Le dossier doit être persistant : sur un
# disque éphémère (tier gratuit Render), les avatars disparaissent au redémarrage.
MEDIA_URL = 'media/'

MEDIA_ROOT = os.getenv("DJANGO_MEDIA_ROOT", "/media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = { # for jwt
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

AUTH_USER_MODEL = 'pong.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Le frontend et l'API vivent sur deux hôtes distincts : le retour de l'OAuth 42
# doit renvoyer le navigateur vers le frontend, pas vers l'API.
FRONTEND_URL = os.getenv("FRONTEND_URL", "").rstrip("/")

# URL publique de cette API, telle que 42 la connaît dans l'application OAuth.
PUBLIC_API_URL = os.getenv("PUBLIC_API_URL", "").rstrip("/")

FT_CLIENT_ID = os.getenv("FT_CLIENT_ID")
FT_CLIENT_SECRET = os.getenv("FT_CLIENT_SECRET")
