FROM elasticsearch:8.14.1

RUN mv /usr/share/elasticsearch/config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml.old

COPY config/elasticsearch.yml /usr/share/elasticsearch/config/

